server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/slims?characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  type-aliases-package: com.example.demo.lims.vo
  mapper-locations: mapper/*.xml

logging:
  level:
    com.example.demo.lims.mapper: debug